services:
  tts:
    build: .
    container_name: tts
    restart: unless-stopped
    env_file: .env
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tts.rule=Host(`tts.daniszwarc.cloud`)"
      - "traefik.http.routers.tts.entrypoints=websecure"
      - "traefik.http.routers.tts.tls.certresolver=mytlschallenge"
      - "traefik.http.services.tts.loadbalancer.server.port=8000"

networks:
  n8n_default:
    external: true
